language: go

go_import_path: github.com/alexeysoshin/smali2java
go:
 - "1.13"
env:
 - DEBUG=false
 - CODECOV_TOKEN="50f4959a-734c-4cd3-af19-4d74004bd7d3"
install:
 - go install
script:
 - go test -v ./... -race -coverprofile=profile.out -covermode=atomic
after_success:
 - bash <(curl -s https://codecov.io/bash)