language: go

go_import_path: github.com/alexeysoshin/smali2java
go:
 - "1.18"
install:
 - go install
script:
 - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
after_success:
 - bash <(curl -s https://codecov.io/bash)