language: go

go_import_path: github.com/alexeysoshin/smali2java
go:
 - "1.13"
env:
 - DEBUG=false
install:
 - go install
script:
 - go test -v ./... -race -coverprofile=profile.out -covermode=atomic
after_success:
 - bash <(curl -s https://codecov.io/bash)