package smali

const (
	Class            = ".class"
	ReturnVoid       = "return-void"
	Return           = "return"
	End              = ".end"
	Method           = ".method"
	Field            = ".field"
	Super            = ".super"
	ConstString      = "const-string"
	InvokeStatic     = "invoke-static"
	InvokeVirtual    = "invoke-virtual"
	ReturnObject     = "return-object"
	Const4           = "const/4"
	SPutBoolean      = "sput-boolean"
	SPut             = "sput"
	SPutObject       = "sput-object"
	SGet             = "sget"
	SGetObject       = "sget-object"
	MoveResult       = "move-result"
	MoveResultObject = "move-result-object"
	InvokeInterface  = "invoke-interface"
	Arrow            = "->"
	IfEqz            = "if-eqz"
	Goto             = "goto"
	TryStart         = ":try_start"
	Implements       = ".implements"
	Final            = "final"
	Synthetic        = "synthetic"
	Bridge           = "bridge"
	VarArgs          = "varargs"
	Enum             = "enum"
	IPutObject	     = "iput-object"
)
